### ISSUE TITLE
Error in defining board file

### ISSUE THREAD

**Issue by Masoudzn** [Joanguitar/Adaptive-Codebook-Optimization#1]
Hello, 

When I try to run 'RunExperiments_2Dev.py' file I see the following error: 

```
Traceback (most recent call last):
  File "RunExperiments_2Dev.py", line 85, in <module>
    BRD.define_BP(methods[0]._codebook, np.arange(0, 64))
  File "/home/masoud/eclipse-workspace/ACO/TalonPy/boardfile.py", line 69, in define_BP
    np.set_printoptions(threshold=np.nan)
  File "/home/masoud/.local/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 246, in set_printoptions
    floatmode, legacy)
  File "/home/masoud/.local/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 93, in _make_options_dict
    raise ValueError("threshold must be numeric and non-NAN, try "
ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation
```
When I change `np.set_printoptions(threshold=np.nan)` in line 69 of boardfile.py to `np.set_printoptions(threshold=sys.maxsize)` the error goes away but the experiments stop at iteration 1. 

I use the ethernet connection to connect the routers to the computer that controls them. The IP addresses of the routers are changed accordingly and the connections are successful. 

What can cause this error? 

Thanks.

**Comment by JasperZhang96** [comment]
Hello Masoudzn,do you know how to solve it?I have the same problem.

**Comment by Joanguitar** [comment]
Hi,

Sorry for my extremely late reply, I've not been paying attention to my Github.
I'm sorry you had problems with the brd files.
The problem is that over different firmware versions the brd file formatting changed as well as the measurements output, so it's really hard to account for all the different version.
I understand that for the moment I wrote the code my skills in Python where far from being acceptable and thus trying to adapt by yourselves to your devices capabilities may be hell.
That's why I released a new code that doesn't depend on a specific hardware and it's more readable.
Instead it has a data pipeline from which you can extract the codebook to measure at each iteration by passing your device's measured data.
Here you can find it:
[ACO](https://github.com/Joanguitar/ACO)
Sorry again for not realizing this section of Github existed.

Best regards.

**Comment by salmanmohebi** [comment]
@Joanguitar,
Would it be possible to specify which version of firmware you had used for your experiment?
I tried with several versions but still got the same error as Masoudzn.
